### ISSUE TITLE
Yahoo Finance API is gone

### ISSUE THREAD

**Issue by killerbutterfly2** [ewenchou/alexa-stock-quotes#1]
It appears as though [the Yahoo API used in the code is gone](http://stackoverflow.com/questions/38355075/has-yahoo-finance-web-service-disappeared-api-changed-down-temporarily).  There doesn't appear to be a lot of good alternatives but maybe [this](http://dev.markitondemand.com/MODApis/) would work?

**Comment by ewenchou** [comment]
Yes, it seems both Yahoo and Google seem to have both shutdown their finance APIs. The one you linked has Terms of Use that prohibit the use in this project. Basically you  need to be a "prospective employee" or have their explicit permission. I'm still digging around to see if there is any free and suitable alternative. Thanks for letting me know.

**Comment by ewenchou** [comment]
OK, found a Python module that uses Google Finance: https://github.com/hongtaocai/googlefinance
Updated my code to use it instead.
